import { useState, useCallback } from "react";
import { useDropzone } from "react-dropzone";
import { Upload, FileAudio, Mic, Play, Loader2, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";

export function AudioPanel() {
  const [file, setFile] = useState<File | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [transcript, setTranscript] = useState("");

  const onDrop = useCallback((acceptedFiles: File[]) => {
    const selected = acceptedFiles[0];
    if (selected) {
      setFile(selected);
      setTranscript("");
      toast({
        title: "Audio file loaded",
        description: `Ready to transcribe: ${selected.name}`,
      });
    }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'audio/*': ['.mp3', '.wav', '.m4a', '.ogg']
    },
    maxFiles: 1
  });

  const handleTranscribe = async () => {
    if (!file) return;
    
    setIsProcessing(true);
    setProgress(0);

    // Simulation of processing
    const interval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 100) {
          clearInterval(interval);
          return 100;
        }
        return prev + 5;
      });
    }, 200);

    setTimeout(() => {
      clearInterval(interval);
      setIsProcessing(false);
      setProgress(100);
      setTranscript(
        "This is a simulated transcription of the audio file. In a real implementation, this text would be generated by the Groq API using the Whisper model. The system has successfully processed the audio input and converted speech to text with high accuracy."
      );
      toast({
        title: "Transcription complete",
        description: "Audio has been successfully processed.",
      });
    }, 4500);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-full">
      <div className="space-y-6">
        <div 
          {...getRootProps()} 
          className={`
            border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-all duration-200
            flex flex-col items-center justify-center h-[300px]
            ${isDragActive ? 'border-primary bg-primary/5' : 'border-border hover:border-primary/50 hover:bg-muted/50'}
            ${file ? 'bg-muted/30' : ''}
          `}
        >
          <input {...getInputProps()} />
          
          {file ? (
            <div className="space-y-4 animate-in fade-in zoom-in duration-300">
              <div className="bg-primary/10 p-4 rounded-full mx-auto w-fit">
                <FileAudio className="h-8 w-8 text-primary" />
              </div>
              <div>
                <p className="font-medium text-lg">{file.name}</p>
                <p className="text-sm text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
              </div>
              <Button variant="outline" size="sm" onClick={(e) => { e.stopPropagation(); setFile(null); }}>
                Remove File
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="bg-muted p-4 rounded-full mx-auto w-fit">
                <Upload className="h-8 w-8 text-muted-foreground" />
              </div>
              <div>
                <p className="font-medium text-lg">Drop audio file here</p>
                <p className="text-sm text-muted-foreground mt-1">or click to browse</p>
              </div>
              <div className="flex gap-2 justify-center pt-2">
                <span className="text-xs bg-muted px-2 py-1 rounded">MP3</span>
                <span className="text-xs bg-muted px-2 py-1 rounded">WAV</span>
                <span className="text-xs bg-muted px-2 py-1 rounded">M4A</span>
              </div>
            </div>
          )}
        </div>

        <div className="flex gap-4">
          <Button 
            className="flex-1 h-12 text-base" 
            disabled={!file || isProcessing}
            onClick={handleTranscribe}
          >
            {isProcessing ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Processing Audio...
              </>
            ) : (
              <>
                <Mic className="mr-2 h-4 w-4" />
                Start Transcription
              </>
            )}
          </Button>
        </div>

        {isProcessing && (
          <div className="space-y-2 animate-in fade-in slide-in-from-top-2">
            <div className="flex justify-between text-sm text-muted-foreground">
              <span>Transcribing...</span>
              <span>{progress}%</span>
            </div>
            <Progress value={progress} className="h-2" />
          </div>
        )}
      </div>

      <div className="h-full min-h-[300px] lg:min-h-auto flex flex-col">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold flex items-center gap-2">
            <FileText className="h-4 w-4 text-primary" />
            Transcription Output
          </h3>
          <Button variant="ghost" size="sm" onClick={() => { navigator.clipboard.writeText(transcript); toast({ title: "Copied to clipboard" }); }} disabled={!transcript}>
            Copy Text
          </Button>
        </div>
        <Card className="flex-1 p-0 overflow-hidden border-muted bg-muted/10">
          <Textarea 
            className="h-full w-full resize-none border-0 focus-visible:ring-0 p-6 font-mono text-sm leading-relaxed bg-transparent"
            placeholder="Transcription will appear here..."
            value={transcript}
            readOnly
          />
        </Card>
      </div>
    </div>
  );
}